#!/bin/bash
#
#

if [ -z "$1" ]; then
    echo "Usage: $0 [--flush] [--del] ports..."
    exit 0
fi

FLUSH=false
OP=-A
DRY=""
while case "$1" in
        --flush)
            FLUSH=true
            ;;
        --del)
            OP=-D
            ;;
        --dryrun)
            DRY="echo"
            ;;
        --*)
            echo "ERROR: Unknown Option $1"
            exit 1
            ;;
        *)
            false
            ;;
    esac; do
    shift
done

if [ "$FLUSH" = "true" ]; then
    $DRY iptables -t raw -f prerouting
    $DRY iptables -t raw -F OUTPUT
fi

while [ -n "$1" ]; do
    PROTO=$(echo "$1" | cut -s -d/ -f2)
    if [ -z "$PROTO" ]; then
        PROTO=tcp
    fi
    PORT=$(echo "$1" | cut -d/ -f1)

    $DRY iptables -t raw $OP PREROUTING \
        -p "$PROTO" --dport "$PORT" \
        -m comment --comment ACCT
    $DRY iptables -t raw $OP OUTPUT \
        -p "$PROTO" --sport "$PORT" \
        -m comment --comment ACCT

    shift
done
